//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partify.Shared.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Partify.Shared.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;context&quot;:{&quot;uri&quot;:&quot;spotify:artist:4UXqAaa6dQYAk18Lv7PEgX&quot;,&quot;metadata&quot;:{}},&quot;bitrate&quot;:0,&quot;position&quot;:9834,&quot;duration&quot;:275460,&quot;paused&quot;:true,&quot;shuffle&quot;:false,&quot;repeat_mode&quot;:0,&quot;track_window&quot;:{&quot;current_track&quot;:{&quot;id&quot;:&quot;6MWODwIhaEYqa994aF20My&quot;,&quot;uri&quot;:&quot;spotify:track:6MWODwIhaEYqa994aF20My&quot;,&quot;type&quot;:&quot;track&quot;,&quot;linked_from_uri&quot;:null,&quot;linked_from&quot;:{&quot;uri&quot;:null,&quot;id&quot;:null},&quot;media_type&quot;:&quot;audio&quot;,&quot;name&quot;:&quot;(Coffee&apos;s For Closers)&quot;,&quot;duration_ms&quot;:275460,&quot;artists&quot;:[{&quot;name&quot;:&quot;Fall Out Boy&quot;,&quot;uri&quot;:&quot;spotify:artist:4UXqAaa6dQYAk18Lv7PEgX&quot;}],&quot;album&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpotifyStateJson {
            get {
                return ResourceManager.GetString("SpotifyStateJson", resourceCulture);
            }
        }
    }
}
